### ISSUE TITLE
feat: add key concepts of module 1

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/progress-tracker#23]
On our curriculum page, we will summarize key concepts of each module. I think bullet points makes the most sense, but if there is a different way you would like to present the information, please share your ideas.

Add a heading element and a list of key concepts in module 1.

**Comment by eram23** [comment]
Can I work on this one pls.

**Comment by michaella23** [comment]
@eram23 that would be great, thanks!

**Comment by eram23** [comment]
Im thinking of doing something like this:
<h1>Scrimba Bootcamp Curriculum</h1>
<h2>Module 1 - Web Dev Basics</h2>
        <ul>
            <li>Learn basics of HTML & CSS</li>
            <li>Create layouts & style them</li>
            <li>Build a Googe.com clone</li>
            <li>Build your first Solo Project</li>
        </ul>

**Comment by michaella23** [comment]
@eram23 that's a good outline! Just wanted to point out that "Web Dev Basics" is Module 2. Let me know if you still want to work on this issue, or switch to #24 . Either way, you might be interested in referencing [notes from Shant's CPR series](https://whimsical.com/frontend-career-path-module-summaries-DhWU21sDa693XnAbhL6DA7), though you don't have to. 🙂

**Comment by eram23** [comment]
Sure! I don't mind doing  one and two if thats ok!
