### ISSUE TITLE
docs: add screenshot for forking the repo

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/progress-tracker#30]
In CONTRIBUTING.md, there is a comment on line 7 to add a screenshot. This will be a screenshot of the main repository page, with the 'Fork' button highlighted/circled/pointed to.

**Comment by pnations** [comment]
@michaella23 Hey Micha, can I help with this issue?

**Comment by michaella23** [comment]
@pnations that would be great! Go for it!
