### ISSUE TITLE
docs: add a Code of Conduct file

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/progress-tracker#31]
Read the [GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) for adding a Code of Conduct to a project, and follow the steps listed there. You can use a template or we can create our own. Tag another contributor in a comment to have them review it, then ask them to do the same.

**Comment by paulaFenner** [comment]
Hey @michaella23, 
I'd like to give this one a try.

**Comment by michaella23** [comment]
Hi @paulaFenner! Thank you. I will assign it to you.

**Comment by michaella23** [comment]
> Tag another contributor in a comment to have them review it, then ask them to do the same.

I don't know if this will be possible, actually. I think you can only tag another user if they have engaged with this issue previously.

**Comment by paulaFenner** [comment]
Ok! So, once I reach the review part, I'll ask on Discord if anyone would be available/interested in joining the issue.

**Comment by paulaFenner** [comment]
Hey @michaella23 ,
I finally got it to work, and more or less understood what I was doing differently. 

Do you accept to have your GitHub linked as the leader for code enforcement?

**Comment by michaella23** [comment]
> Do you accept to have your GitHub linked as the leader for code enforcement?

Absolutely. Thanks @paulaFenner!

**Comment by paulaFenner** [comment]
Hey @fame372 ,
could you please review the code of conduct, and then ask another contributor to do the same?
The intention is that all contributors get to read the code of conduct.

Thank you :)

**Comment by paulaFenner** [comment]
Thank you, @fame372 !

I think sending a message to everyone is a great idea.
I would only suggest to add the instruction that the contributor should come to this issue and confirm they have read the COC. What do you think? :)

**Comment by fame372** [comment]
@paulaFenner 
That is a good Idea, by the way the code of conduct look very well written and easy to understand. Great job .
have a good weekend

**Comment by paulaFenner** [comment]
@fame372 
Thanks! I hope you had an awesome weekend too.
I can't take credit for the code of conduct—it’s straight from the GitHub docs. 😄
