### ISSUE TITLE
style: add CSS custom properties for the color scheme

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/progress-tracker#45]
One of our contributors created a design template for this project in [Figma](https://www.figma.com/design/QqjrkFiItVbK9ns2MGjtIK/Scrimba-Bootcamp-Project-Tracker?node-id=3-1609&t=kwddFR573lWFlJUq-0). In that file you will see a node called 'Color Palette'. You can look at each child node there for the name and the hex code of that color.
In `index.css`, add a root selector and add **[CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)** to define our color palette. Add a body selector in the CSS and define its `background-color` with one of these custom variables.
(Note: if #46 has not been completed,  you will not be able to see this change when you run the project locally.)

**Comment by giu3337** [comment]
@michaella23 Hi Micha id love help with this

**Comment by michaella23** [comment]
Great, go for it @giu3337! 😊

**Comment by michaella23** [comment]
@giu3337 if you are still working on this, please be aware that we have had some code added to `index.css` since you requested. 🙂 So if you have already forked our repository, cloned it, and added the remote upstream, you will want to pull down changes from our main repo. You can do this in the terminal with the command: `git pull upstream main`.

**Comment by giu3337** [comment]
Awesome @michaella23 thank you so much I am reading the doc now and see how everything works! Thank you for everything!
