### ISSUE TITLE
feat: Add `header` and `nav` elements

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/progress-tracker#49]
Each page will have a header with the name of our app and a nav element.  Add the code for these. Right now let's just hard code it in each of the HTML files. You can add some styles, but if our desktop and mobile `nav` elements are going to display differently, we should break this up into sub-tasks with associated Issues.
Create a new Discussion here on GitHub and/or on Discord to talk about the styles we will use, if we are going to build this app mobile-first, or start with our desktop styles. You can create a new issue for styling the nav for a different viewport width.

**Comment by othukeodoko** [comment]
Hi Micha, I would like to collaborate on this

**Comment by michaella23** [comment]
@othukeodoko You can start on this after your PR for issue #46 is merged. Let's post in the collaborative-work channel on Discord to see if other people have a preference about building mobile first.
