### ISSUE TITLE
feat: Add hero section in index.html

### ISSUE THREAD

**Issue by rabin-thami** [ScrimbaBootcamp/progress-tracker#54]
Hey @michaella23 I would like to add hero section in out index.html page 

- [x] Background Image 
- [x] Feature Text
- [x] Site Description
- [x] CTA Button

**Comment by michaella23** [comment]
This sounds fantastic! Thanks @rabin-thami. 🙂

**Comment by rabin-thami** [comment]
@michaella23  i just did a PR

**Comment by BastienWinant** [comment]
@rabin-thami @michaella23 small order of business: the closing </section> tag seems to be missing for the hero section in /index.html

**Comment by michaella23** [comment]
Wow. Good catch @BastienWinant ! Sorry if that was creating issues for you.
