### ISSUE TITLE
feat: add little animation in hover state in navbar 

### ISSUE THREAD

**Issue by rabin-thami** [ScrimbaBootcamp/progress-tracker#67]
hey @othukeodoko  i want to change a little bit your code and also want to add the hover state transition animation. 
@michaella23

**Comment by michaella23** [comment]
I think hover, focus, and active states for links would be great! Transition animation sounds really nice. Thanks @rabin-thami

**Comment by othukeodoko** [comment]
Sure @rabin-thami go ahead!

**Comment by michaella23** [comment]
PR #68 closes this issue.
