### ISSUE TITLE
fix: fix typo in curriculum.html

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/progress-tracker#77]
There is a typo on line 51. Follow the git workflow for this project and submit a PR to fix this typo. Good first issue!

**Comment by Samcraig77** [comment]
Please assign this to me :)

**Comment by michaella23** [comment]
You got it! @Samcraig77

**Comment by Samcraig77** [comment]
Hey @michaella23 can you please close this 😊
