### ISSUE TITLE
Add nav bar to contributors.html

### ISSUE THREAD

**Issue by Samcraig77** [ScrimbaBootcamp/progress-tracker#97]
contributors.html needs a the new nav bar linked to it, with the nav menu changed

**Comment by Samcraig77** [comment]
@michaella23 I can take care of this

**Comment by michaella23** [comment]
I think PR #98 closes this, right @Samcraig77 ?

**Comment by Samcraig77** [comment]
Right you are @michaella23, thanks for the heads up 😊
